### ISSUE TITLE
git diff problem to know modified same file

### ISSUE THREAD

**Issue by Pritesh23** [githubteacher/intermediate-april-2015#26]
After git reset HEAD test.txt ?? What we need to do ? Because when i wrote git diff - its empty

**Comment by githubteacher** [comment]
keep in mind that git diff only works when there are differences between the working directory and the HEAD - otherwise, you may need to make some changes or use one of the other options to indicate specific files or commits to compare. Here is some [documentation](https://github.com/githubteacher/intermediate-april-2015/issues/23) to help you learn more!
