### ISSUE TITLE
SHA-1 outputs 120 "unique random" bits per file.  50% chance of collision between two files is 1/2^60 probability.

### ISSUE THREAD

**Issue by aalten** [githubteacher/intermediate-april-2015#27]
The estimated number of atoms in the Universe is 2^50.

**Comment by pcharlan** [comment]
This isn't particularly important :), but SHA-1 is 160 bits; Google thinks 10^80 is the estimate for hydrogen atoms in the universe, which is about 2^265.  Though 1/2^60 is approximately the number of objects you need for a 50% probability of a SHA1 collision (due to weaknesses in the algorithm), it's not itself a probability.
